# Generated by Django 4.1.5 on 2023-02-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=400)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(default='', max_length=40)),
                ('pic', models.ImageField(default='static/images/defaulimage.png', upload_to='donor/')),
                ('status', models.CharField(default='pending', max_length=30)),
            ],
            options={
                'db_table': 'donor',
            },
        ),
    ]
