# Generated by Django 4.1.5 on 2023-03-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('disease', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=400)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
