# Generated by Django 4.1.5 on 2023-03-25 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30)),
                ('patient_age', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=20)),
                ('nature', models.CharField(max_length=50)),
                ('unit', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('request_by_donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blood.donor')),
                ('request_by_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blood.patient')),
            ],
            options={
                'db_table': 'blood_request',
            },
        ),
    ]
